#!/bin/bash

WHI="$(tput setaf 7)"
GRE="$(tput setaf 2)"
RED="$(tput setaf 1)"

clear
echo -en "${WHI}"
cat <<'EOF'
PISTAR-LASTQSO INSTALLATION:

This install script will perform the following operations...

1.) remount the rootfs as read-write

2.) copy "pistar-lastqso" to /usr/local/bin and enable execute permission

3.) copy "dxcc.pl" script to /usr/local/bin and enable execute permission

4.) install the package "figlet" from the standard repositories using
    "sudo apt-get -y install figlet"

5.) install the package "jq" from the standard repositories using
    "sudo apt-get -y install jq"

6.) copy the supplemental "ansi_shadow.flf" font file to /usr/share/figlet

7.) remount the rootfs as read-only

EOF
echo -en "Press ENTER to proceed, or Ctrl-C to abort... "
read FOO

echo -e "Beginning install."

#----------
echo -e "${GRE}Step 1. - Mounting rootfs filesystem as read-write...${WHI}"
sudo mount -o remount,rw /

#----------
echo -e "${GRE}Step 2. - Installing the pistar-lastqso script...${WHI}"
if [ ! -f ./pistar-lastqso ]
then
  echo -e "${RED}\n  Error... pistar-lastqso not found in current directory.${WHI}"
  echo -e "${RED}  Installation failed.\n${WHI}"
  exit
else
  if [ -f /usr/local/sbin/pistar-lastqso ]
  then
    sudo rm /usr/local/sbin/pistar-lastqso 2> /dev/null
  fi
  if [ "$(sudo cp ./pistar-lastqso /usr/local/bin 2> /dev/null)" ]
  then
    echo -e "${RED}\n  Unable to copy script to /usr/local/bin.${WHI}"
    echo -e "${RED}  Installation failed.\n${WHI}"
    exit
  fi
  if [ "$(sudo chmod +x /usr/local/bin/pistar-lastqso 2> /dev/null)" ]
  then
    echo -e "${RED}\n  Unable to set execute permission.${WHI}"
    echo -e "${RED}  Installation failed.\n${WHI}"
    exit
  fi
fi

#----------
echo -e "${GRE}Step 3. - Installing the dxcc.pl script...${WHI}"
if [ ! -f ./dxcc.pl ]
then
  echo -e "${RED}\n  Error... dxcc.pl not found in current directory.${WHI}"
  echo -e "${RED}  Installation failed.\n${WHI}"
  exit
else
  if [ "$(sudo cp ./dxcc.pl /usr/local/bin 2> /dev/null)" ]
  then
    echo -e "${RED}\n  Unable to copy script to /usr/local/bin.${WHI}"
    echo -e "${RED}  Installation failed.\n${WHI}"
    exit
  fi
  if [ "$(sudo chmod +x /usr/local/bin/dxcc.pl 2> /dev/null)" ]
  then
    echo -e "${RED}\n  Unable to set execute permission.${WHI}"
    echo -e "${RED}  Installation failed.\n${WHI}"
    exit
  fi
fi

#----------
if [ -n "$(command -v figlet)" ]
then
  echo -e "${GRE}Step 4. - Figlet is already installed.  Continuing...${WHI}"
else
  echo -e "${GRE}Step 4. - Installing figlet from the repositories...${WHI}"
  sudo apt-get -y install figlet
fi

#----------
if [ -n "$(command -v jq)" ]
then
  echo -e "${GRE}Step 5. - jq is already installed.  Continuing...${WHI}"
else
  echo -e "${GRE}Step 5. - Installing jq from the repositories...${WHI}"
  sudo apt-get -y install jq
fi

#----------
if [ ! -f /usr/share/figlet/ansi_shadow.flf ]
then
  if [ ! -f ./ansi_shadow.flf ]
  then
    echo -e "${RED}\n  Error... ansi_shadow.flf not found in current directory.${WHI}"
    echo -e "${RED}  Installation failed.\n${WHI}"
    exit
  else
    echo -e "${GRE}Step 6. - Installing ansi_shadow font...${WHI}"
    if [ "$(sudo cp ./ansi_shadow.flf /usr/share/figlet/ansi_shadow.flf 2> /dev/null)" ]
    then
      echo -e "${RED}\n  Unable to copy ansi_shadow.flf to /usr/share/figlet${WHI}"
      echo -e "${RED}  Installation failed.\n${WHI}"
      exit
    fi
  fi
else
  echo -e "${GRE}Step 6. - Font file is already installed.  Continuing...${WHI}"
fi

#----------
echo "${GRE}Step 7. - Returning rootfs filesystem to read-only...${WHI}"
sync ; sync ; sync
sudo mount -o remount,rw /

#----------
echo -e "${WHI}\nInstallation complete."
tput sgr0

